### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by WhyFaust** [rogeraabbccdd/CSGO-Chicken-Pet#1]
1)Add a set of HP to the pet
2)Add a set of Speed to the pet
3)Add a set of Model to the pet
4)Add a custom command ( Eg stand still, or to go there (on aim), maybe attack, e t c

**Comment by rogeraabbccdd** [comment]
1. No, I think players will kill others chicken, that's bad.
2. It's possible, but I don't like this idea. It's just a chicken.
3. No, this plugin is for chicken, I have planned to add particles and colors in the future. But I think I can edit [this plugin](https://forums.alliedmods.net/showthread.php?t=259823) for you if I have time.
4. Maybe possible with SDKCall.
