### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by DataWorm** [rogeraabbccdd/CSGO-Chicken-Pet#2]
In its current version I can't compile your script locally because it can't find the dependency "kento_csgocolors". However replacing it with the default "colors" integrated in sourcemod seem to work just fine.

**Comment by DataWorm** [comment]
Ah my bad, now I see replacing the library doesn't work. Well it compiles but colors don't work ingame. ;-)

**Comment by rogeraabbccdd** [comment]
https://github.com/rogeraabbccdd/Kento-Rankme/blob/master/scripting/include/kento_csgocolors.inc
